services:
  # =========================================
  # 1. Redis 缓存与消息队列服务
  # -----------------------------------------
  redis:
    image: redis:7
    container_name: mhd-boot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .\docker-data\redis\data:/data
      - .\docker-data\redis\conf:/etc/redis
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # =========================================
  # 2. MinIO 对象存储服务
  # -----------------------------------------
  # 作用：
  #   - 存储非结构化数据
  # =========================================
  minio:
    image: minio/minio
    container_name: mhd-boot-minio
    # 启动命令：指定数据目录和控制台地址
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .\docker-data\minio\data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # =========================================
  # 3. MinIO 初始化任务 (Init Container Pattern)
  # -----------------------------------------
  # 作用：
  #   - 自动创建项目所需的存储桶 (Bucket)
  #   - 设置存储桶的访问权限
  # =========================================
  createbuckets:
    image: minio/mc
    container_name: mhd-boot-minio-init
    depends_on:
      minio:
        condition: service_healthy # 必须等待 MinIO 服务健康（不仅仅是启动）
    entrypoint: >
      /bin/sh -c "
      # 1. 配置 MinIO 客户端别名 (myminio) 连接到 minio 服务
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      # 2. 创建名为 mhd-boot 的存储桶
      /usr/bin/mc mb myminio/mhd-boot;
      # 3. 设置该存储桶为公共读权限（方便前端直接访问图片等资源）
      /usr/bin/mc anonymous set public myminio/mhd-boot;
      exit 0;
      "
