<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mhd</groupId>
        <artifactId>mhd-boot</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>libs</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>boot-common</module>
        <module>boot-common-doc</module>
        <module>boot-common-mybatis</module>
        <module>boot-common-web</module>
        <module>boot-common-sftp</module>
        <module>boot-common-security</module>
        <module>boot-common-job</module>
        <module>boot-common-operatelog</module>
        <module>boot-common-idempotent</module>
        <module>boot-common-redis</module>
        <module>boot-common-sse</module>
        <module>boot-common-excel</module>
    </modules>

</project>